"""SAR (Suspicious Activity Report) draft formatter."""

from __future__ import annotations

from datetime import datetime, timezone


def format_sar(case: dict) -> str:
    """Generate a structured SAR draft from a DB investigation row."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    flags = case.get("flags") or []
    flags_text = (
        "\n".join(f"  {i + 1}. {f}" for i, f in enumerate(flags))
        if flags
        else "  None identified"
    )

    confidence = case.get("confidence")
    confidence_pct = f"{int(float(confidence) * 100)}%" if confidence is not None else "N/A"

    return (
        f"SUSPICIOUS ACTIVITY REPORT DRAFT\n"
        f"Generated: {now}\n"
        f"Case ID: {case['case_id']}\n"
        f"Classification: CONFIDENTIAL\n"
        f"\n"
        f"SUBJECT INFORMATION\n"
        f"Entity: {case['case_id']}\n"
        f"Alert Type: {case.get('alert_type', 'Unknown')}\n"
        f"Amount: {case.get('currency', 'INR')} {case.get('amount', 'Unknown')}\n"
        f"\n"
        f"SUSPICIOUS ACTIVITY DESCRIPTION\n"
        f"{case.get('investigation_narrative', 'Not available')}\n"
        f"\n"
        f"RISK FACTORS\n"
        f"{flags_text}\n"
        f"\n"
        f"ANALYST RISK ASSESSMENT\n"
        f"{case.get('risk_assessment', 'Not available')}\n"
        f"\n"
        f"RECOMMENDED ACTION: {case.get('recommended_action', 'Unknown')}\n"
        f"AI Confidence: {confidence_pct}\n"
        f"\n"
        f"---\n"
        f"This draft was generated by FraudOS AI Investigation Platform.\n"
        f"Final SAR filing requires analyst review and approval."
    )
