const BASE = import.meta.env.VITE_API_URL || 'http://localhost:8000';
const getKey = () => sessionStorage.getItem('fraudos_key') || '';
export const api = {
  post: (path, body) => fetch(`${BASE}${path}`, {
    method:'POST', headers:{'Content-Type':'application/json','X-API-Key':getKey()},
    body:JSON.stringify(body)
  }).then(r => r.json()),
  get: (path) => fetch(`${BASE}${path}`, { headers:{'X-API-Key':getKey()} }).then(r => r.json()),
};
export const MOCK_CASES = [
  { case_id:'CASE-001', alert_type:'UPI_FRAUD', risk_level:'HIGH', risk_score:87, recommended_action:'ESCALATE', amount:49500, currency:'INR', received_at:'2024-06-01T02:14:00Z', investigation_narrative:'Account opened 12 days ago initiated ₹49,500 UPI transfer just below reporting threshold at 2AM to unknown payee. Classic structuring pattern.', flags:['Threshold structuring','New account','Unusual hour'], confidence:0.91, entity_profile:{summary:'New account, 12 days old, no prior transaction history',risk_indicators:['New account','No payee history'],account_age_assessment:'High risk'}, transaction_pattern:{pattern_type:'Threshold structuring',anomalies:['Amount ₹49,500 — just below ₹50,000 CTR limit','Transaction at 02:14 AM'],velocity_assessment:'Single high-value transaction on new account'}, risk_assessment:'Transaction exhibits classic threshold-structuring behavior. New account with no history initiating a near-threshold UPI transfer to an unregistered payee at 2AM presents high fraud probability.', processing_time_ms:1840, model_used:'claude-opus-4-6' },
  { case_id:'CASE-002', alert_type:'CARD_FRAUD', risk_level:'CRITICAL', risk_score:96, recommended_action:'BLOCK', amount:285000, currency:'INR', received_at:'2024-06-01T03:45:00Z', investigation_narrative:'International card transaction of ₹2,85,000 on an account dormant for 8 months. Geolocation mismatch — card used in Dubai while account holder is India-based.', flags:['Geo mismatch','Dormant account','High value international'], confidence:0.97, entity_profile:{summary:'Account dormant for 8 months, reactivated with international transaction',risk_indicators:['8 months dormant','Geolocation mismatch'],account_age_assessment:'Established account, suspicious reactivation'}, transaction_pattern:{pattern_type:'International card fraud',anomalies:['Geolocation: Dubai vs India-registered','Account dormant 8 months','₹2.85L single transaction'],velocity_assessment:'First transaction after 8-month dormancy is high-value international'}, risk_assessment:'Dormant account reactivated with a high-value international transaction from a mismatched geolocation is a strong indicator of card compromise or account takeover.', processing_time_ms:1620, model_used:'claude-opus-4-6' },
  { case_id:'CASE-003', alert_type:'AML', risk_level:'HIGH', risk_score:82, recommended_action:'ESCALATE', amount:48000, currency:'INR', received_at:'2024-06-01T10:20:00Z', investigation_narrative:'Three structured deposits of ₹48,000 within 6 hours across different branches. Pattern consistent with smurfing — deliberate fragmentation to avoid ₹50,000 CTR threshold.', flags:['Smurfing pattern','Multiple branches','CTR avoidance'], confidence:0.88, entity_profile:{summary:'Account with multiple same-day structured deposits',risk_indicators:['Structured deposits','Multi-branch activity'],account_age_assessment:'Medium-aged account, unusual deposit pattern'}, transaction_pattern:{pattern_type:'Smurfing / Structuring',anomalies:['3 deposits of ₹48,000 within 6 hours','Deposits at 3 different branches','All amounts just below ₹50,000 CTR limit'],velocity_assessment:'High velocity structured deposits — deliberate fragmentation'}, risk_assessment:'Three identical near-threshold cash deposits at different branches within 6 hours is a textbook smurfing pattern. Recommend SAR filing and enhanced due diligence.', processing_time_ms:2100, model_used:'claude-opus-4-6' },
  { case_id:'CASE-004', alert_type:'ACCOUNT_TAKEOVER', risk_level:'CRITICAL', risk_score:94, recommended_action:'BLOCK', amount:150000, currency:'INR', received_at:'2024-06-01T11:05:00Z', investigation_narrative:'Device fingerprint changed 40 minutes before ₹1,50,000 NEFT transfer. Login from new IP (VPN detected). Password reset and beneficiary addition within same session.', flags:['Device change','VPN detected','New beneficiary','Password reset'], confidence:0.95, entity_profile:{summary:'Account accessed from new device via VPN with immediate high-value transfer',risk_indicators:['New device fingerprint','VPN IP','Same-session beneficiary addition'],account_age_assessment:'Established account — unusual access pattern'}, transaction_pattern:{pattern_type:'Account takeover sequence',anomalies:['Device change 40min before transfer','VPN-masked IP','Password reset + beneficiary + transfer in single session'],velocity_assessment:'Compressed attack sequence — classic ATO pattern'}, risk_assessment:'The sequence of device change, VPN login, password reset, new beneficiary registration, and immediate high-value transfer within a single session is a high-confidence account takeover indicator.', processing_time_ms:1950, model_used:'claude-opus-4-6' },
  { case_id:'CASE-005', alert_type:'SYNTHETIC_IDENTITY', risk_level:'MEDIUM', risk_score:64, recommended_action:'REVIEW', amount:95000, currency:'INR', received_at:'2024-06-01T14:30:00Z', investigation_narrative:'Account with recently activated PAN shows rapid credit utilisation pattern. KYC documents flagged by bureau — address not verifiable. Possible synthetic identity fraud.', flags:['KYC mismatch','Rapid utilisation','Unverifiable address'], confidence:0.72, entity_profile:{summary:'Recently activated PAN with unverifiable KYC documents',risk_indicators:['Bureau KYC flag','Unverifiable address','Rapid credit utilisation'],account_age_assessment:'New account — KYC concerns'}, transaction_pattern:{pattern_type:'Synthetic identity fraud',anomalies:['PAN activated recently','Rapid credit utilisation to 85%','Address unverifiable in bureau records'],velocity_assessment:'Abnormal utilisation speed for new credit account'}, risk_assessment:'The combination of a recently activated PAN, bureau KYC flags, unverifiable address, and rapid credit utilisation is consistent with synthetic identity fraud. Manual KYC re-verification recommended.', processing_time_ms:1780, model_used:'claude-opus-4-6' },
];
