// All requests use relative URLs so the Vite dev proxy (→ :8000) and the
// production reverse-proxy both work without configuration changes.
const BASE = import.meta.env.VITE_API_URL || '';

// Only block explicit non-localhost http:// URLs (relative paths are fine).
const isLocalhost = (url) => !url || /^https?:\/\/(localhost|127\.|0\.0\.0\.0)/.test(url);
const assertHttps = (url) => {
  if (url && url.startsWith('http://') && !isLocalhost(url)) {
    throw new Error('Insecure connection: API URL must use HTTPS in non-local environments');
  }
};

const handle401 = () => {
  window.location.replace('/login');
};

const parseResponse = async (r) => {
  if (r.status === 401) { handle401(); throw new Error('Not authenticated'); }
  if (!r.ok) throw new Error(`Request failed (${r.status})`);
  return r.json();
};

const parseTextResponse = async (r) => {
  if (r.status === 401) { handle401(); throw new Error('Not authenticated'); }
  if (!r.ok) throw new Error(`Request failed (${r.status})`);
  return r.text();
};

export const api = {
  login: async (apiKey) => {
    assertHttps(BASE);
    const r = await fetch(`${BASE}/auth`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify({ api_key: apiKey }),
    });
    if (r.status === 401) throw new Error('Invalid API key');
    if (!r.ok) throw new Error(`Request failed (${r.status})`);
    return r.json();
  },

  checkAuth: () => {
    assertHttps(BASE);
    return fetch(`${BASE}/auth/me`, { credentials: 'include' });
  },

  logout: async () => {
    await fetch(`${BASE}/auth/logout`, { method: 'POST', credentials: 'include' });
    window.location.replace('/login');
  },

  post: (path, body) => {
    assertHttps(BASE);
    return fetch(`${BASE}${path}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify(body),
    }).then(parseResponse);
  },

  get: (path) => {
    assertHttps(BASE);
    return fetch(`${BASE}${path}`, { credentials: 'include' }).then(parseResponse);
  },

  getText: (path) => {
    assertHttps(BASE);
    return fetch(`${BASE}${path}`, { credentials: 'include' }).then(parseTextResponse);
  },
};

export const MOCK_CASES = [
  { case_id:'CASE-001', alert_type:'UPI_FRAUD', risk_level:'HIGH', risk_score:87, recommended_action:'ESCALATE', amount:49500, currency:'INR', received_at:'2024-06-01T02:14:00Z', investigation_narrative:'Account opened 12 days ago initiated ₹49,500 UPI transfer just below reporting threshold at 2AM to unknown payee. Classic structuring pattern.', flags:['Threshold structuring','New account','Unusual hour'], confidence:0.91, entity_profile:{summary:'New account, 12 days old, no prior transaction history',risk_indicators:['New account','No payee history'],account_age_assessment:'High risk'}, transaction_pattern:{pattern_type:'Threshold structuring',anomalies:['Amount ₹49,500 — just below ₹50,000 CTR limit','Transaction at 02:14 AM'],velocity_assessment:'Single high-value transaction on new account'}, risk_assessment:'Transaction exhibits classic threshold-structuring behavior. New account with no history initiating a near-threshold UPI transfer to an unregistered payee at 2AM presents high fraud probability.', processing_time_ms:1840, model_used:'claude-opus-4-6' },
  { case_id:'CASE-002', alert_type:'CARD_FRAUD', risk_level:'CRITICAL', risk_score:96, recommended_action:'BLOCK', amount:285000, currency:'INR', received_at:'2024-06-01T03:45:00Z', investigation_narrative:'International card transaction of ₹2,85,000 on an account dormant for 8 months. Geolocation mismatch — card used in Dubai while account holder is India-based.', flags:['Geo mismatch','Dormant account','High value international'], confidence:0.97, entity_profile:{summary:'Account dormant for 8 months, reactivated with international transaction',risk_indicators:['8 months dormant','Geolocation mismatch'],account_age_assessment:'Established account, suspicious reactivation'}, transaction_pattern:{pattern_type:'International card fraud',anomalies:['Geolocation: Dubai vs India-registered','Account dormant 8 months','₹2.85L single transaction'],velocity_assessment:'First transaction after 8-month dormancy is high-value international'}, risk_assessment:'Dormant account reactivated with a high-value international transaction from a mismatched geolocation is a strong indicator of card compromise or account takeover.', processing_time_ms:1620, model_used:'claude-opus-4-6' },
  { case_id:'CASE-003', alert_type:'AML', risk_level:'HIGH', risk_score:82, recommended_action:'ESCALATE', amount:48000, currency:'INR', received_at:'2024-06-01T10:20:00Z', investigation_narrative:'Three structured deposits of ₹48,000 within 6 hours across different branches. Pattern consistent with smurfing — deliberate fragmentation to avoid ₹50,000 CTR threshold.', flags:['Smurfing pattern','Multiple branches','CTR avoidance'], confidence:0.88, entity_profile:{summary:'Account with multiple same-day structured deposits',risk_indicators:['Structured deposits','Multi-branch activity'],account_age_assessment:'Medium-aged account, unusual deposit pattern'}, transaction_pattern:{pattern_type:'Smurfing / Structuring',anomalies:['3 deposits of ₹48,000 within 6 hours','Deposits at 3 different branches','All amounts just below ₹50,000 CTR limit'],velocity_assessment:'High velocity structured deposits — deliberate fragmentation'}, risk_assessment:'Three identical near-threshold cash deposits at different branches within 6 hours is a textbook smurfing pattern. Recommend SAR filing and enhanced due diligence.', processing_time_ms:2100, model_used:'claude-opus-4-6' },
  { case_id:'CASE-004', alert_type:'ACCOUNT_TAKEOVER', risk_level:'CRITICAL', risk_score:94, recommended_action:'BLOCK', amount:150000, currency:'INR', received_at:'2024-06-01T11:05:00Z', investigation_narrative:'Device fingerprint changed 40 minutes before ₹1,50,000 NEFT transfer. Login from new IP (VPN detected). Password reset and beneficiary addition within same session.', flags:['Device change','VPN detected','New beneficiary','Password reset'], confidence:0.95, entity_profile:{summary:'Account accessed from new device via VPN with immediate high-value transfer',risk_indicators:['New device fingerprint','VPN IP','Same-session beneficiary addition'],account_age_assessment:'Established account — unusual access pattern'}, transaction_pattern:{pattern_type:'Account takeover sequence',anomalies:['Device change 40min before transfer','VPN-masked IP','Password reset + beneficiary + transfer in single session'],velocity_assessment:'Compressed attack sequence — classic ATO pattern'}, risk_assessment:'The sequence of device change, VPN login, password reset, new beneficiary registration, and immediate high-value transfer within a single session is a high-confidence account takeover indicator.', processing_time_ms:1950, model_used:'claude-opus-4-6' },
  { case_id:'CASE-005', alert_type:'SYNTHETIC_IDENTITY', risk_level:'MEDIUM', risk_score:64, recommended_action:'REVIEW', amount:95000, currency:'INR', received_at:'2024-06-01T14:30:00Z', investigation_narrative:'Account with recently activated PAN shows rapid credit utilisation pattern. KYC documents flagged by bureau — address not verifiable. Possible synthetic identity fraud.', flags:['KYC mismatch','Rapid utilisation','Unverifiable address'], confidence:0.72, entity_profile:{summary:'Recently activated PAN with unverifiable KYC documents',risk_indicators:['Bureau KYC flag','Unverifiable address','Rapid credit utilisation'],account_age_assessment:'New account — KYC concerns'}, transaction_pattern:{pattern_type:'Synthetic identity fraud',anomalies:['PAN activated recently','Rapid credit utilisation to 85%','Address unverifiable in bureau records'],velocity_assessment:'Abnormal utilisation speed for new credit account'}, risk_assessment:'The combination of a recently activated PAN, bureau KYC flags, unverifiable address, and rapid credit utilisation is consistent with synthetic identity fraud. Manual KYC re-verification recommended.', processing_time_ms:1780, model_used:'claude-opus-4-6' },
  { case_id:'CASE-006', alert_type:'AML', risk_level:'CRITICAL', risk_score:93, recommended_action:'BLOCK', amount:340000, currency:'INR', received_at:'2024-06-02T08:15:00Z', investigation_narrative:'Account received ₹3,40,000 across 6 inward IMPS transactions from 6 different senders within 90 minutes, then forwarded entire amount to a single recipient within 20 minutes. Classic money mule layering pattern.', flags:['Mule account pattern','Rapid fund aggregation','Immediate outward transfer','Multiple senders'], confidence:0.96, entity_profile:{summary:'Account acting as intermediary — aggregates funds from multiple sources and immediately forwards',risk_indicators:['6 inward transfers in 90 min','Immediate full outward transfer','No retention pattern'],account_age_assessment:'Account used as pass-through — no legitimate activity pattern'}, transaction_pattern:{pattern_type:'Money mule layering',anomalies:['₹3.4L received from 6 senders in 90 minutes','Entire amount forwarded within 20 minutes','Zero fund retention'],velocity_assessment:'Aggregate-and-forward in under 2 hours — no dwell time'}, risk_assessment:'Account exhibits textbook money mule behavior — aggregating funds from multiple sources and immediately layering through to a single recipient with no retention. High-confidence AML violation. SAR filing and account freeze recommended.', processing_time_ms:1710, model_used:'claude-opus-4-6' },
  { case_id:'CASE-007', alert_type:'CARD_FRAUD', risk_level:'HIGH', risk_score:81, recommended_action:'ESCALATE', amount:520000, currency:'INR', received_at:'2024-06-02T11:30:00Z', investigation_narrative:'Corporate account initiated RTGS transfer of ₹5,20,000 to a beneficiary added 2 hours prior. Transfer instruction arrived via email — same domain as CFO but different sending server (homoglyph attack: rn instead of m). Beneficiary account is 4 days old.', flags:['BEC indicator','New beneficiary','Homoglyph email domain','New beneficiary account'], confidence:0.84, entity_profile:{summary:'Corporate account — transfer instruction likely originated from spoofed CFO email',risk_indicators:['Homoglyph domain detected','New beneficiary (4-day account)','2hr add-to-transfer gap'],account_age_assessment:'Established corporate account — social engineering vector suspected'}, transaction_pattern:{pattern_type:'Business Email Compromise',anomalies:['Beneficiary added 2hr before high-value RTGS','Sender domain rn-masquerading-as-m pattern','Beneficiary account 4 days old'],velocity_assessment:'Compressed add-to-transfer window is a BEC hallmark'}, risk_assessment:'Transfer instruction bears hallmarks of Business Email Compromise — spoofed CFO domain, new beneficiary account, and compressed add-to-transfer timing. Recommend calling the CFO directly to verify before processing.', processing_time_ms:2030, model_used:'claude-opus-4-6' },
  { case_id:'CASE-008', alert_type:'SYNTHETIC_IDENTITY', risk_level:'HIGH', risk_score:78, recommended_action:'ESCALATE', amount:200000, currency:'INR', received_at:'2024-06-02T13:45:00Z', investigation_narrative:'Instant loan of ₹2,00,000 sanctioned via mobile app. Applicant\'s Aadhaar address does not match NACH mandate address. Phone number registered 11 days ago. No credit history — bureau score returned as null. Loan proceeds transferred to a different account immediately after disbursal.', flags:['Address mismatch','New phone number','No credit history','Immediate disbursal transfer'], confidence:0.81, entity_profile:{summary:'Loan applicant with mismatched KYC and no credit history — likely synthetic or stolen identity',risk_indicators:['Aadhaar-NACH address mismatch','Phone registered 11 days ago','Null bureau score'],account_age_assessment:'New account — KYC integrity failure'}, transaction_pattern:{pattern_type:'Digital lending fraud',anomalies:['Loan proceeds immediately transferred out post-disbursal','No credit bureau history','KYC address inconsistency'],velocity_assessment:'Disbursal-to-transfer gap under 4 minutes'}, risk_assessment:'KYC address mismatch, newly registered phone number, absent credit history, and immediate disbursal transfer are collectively high-confidence indicators of digital lending fraud using a synthetic or stolen identity.', processing_time_ms:1890, model_used:'claude-opus-4-6' },
  { case_id:'CASE-009', alert_type:'AML', risk_level:'HIGH', risk_score:76, recommended_action:'ESCALATE', amount:89500, currency:'INR', received_at:'2024-06-02T16:20:00Z', investigation_narrative:'Account made 4 UPI payments totalling ₹89,500 to 3 different P2P crypto exchange merchant IDs within 6 hours. Transactions structured to avoid UPI daily limit. Account has no prior crypto-related transactions.', flags:['Crypto on-ramp','P2P exchange transfers','Structuring','No prior crypto history'], confidence:0.79, entity_profile:{summary:'Account with no prior crypto exposure now making structured transfers to P2P crypto merchants',risk_indicators:['4 transfers to crypto merchant IDs','Amounts structured below UPI limits','No prior crypto activity'],account_age_assessment:'Established account — sudden crypto exposure'}, transaction_pattern:{pattern_type:'Crypto layering — structured on-ramp',anomalies:['₹89,500 split across 4 transactions to avoid UPI daily cap','3 different P2P exchange merchant IDs','All within 6-hour window'],velocity_assessment:'Deliberate fragmentation across merchant IDs to avoid detection'}, risk_assessment:'Structured UPI payments to multiple P2P crypto exchange merchant IDs indicate a deliberate layering attempt using cryptocurrency as an intermediary. Pattern is consistent with proceeds of crime being converted to crypto to obscure trail.', processing_time_ms:1660, model_used:'claude-opus-4-6' },
  { case_id:'CASE-010', alert_type:'ACCOUNT_TAKEOVER', risk_level:'CRITICAL', risk_score:91, recommended_action:'BLOCK', amount:75000, currency:'INR', received_at:'2024-06-02T18:05:00Z', investigation_narrative:'Customer called phone banking, passed KYC verbally, and requested OTP-based NEFT of ₹75,000. Call originated from a spoofed number matching the customer\'s registered mobile. Voice pattern analysis flagged potential impersonation. Transfer destination: first-time beneficiary.', flags:['Spoofed caller ID','Voice impersonation flag','First-time beneficiary','Phone banking channel anomaly'], confidence:0.93, entity_profile:{summary:'Legitimate customer account — access gained via phone banking using spoofed caller ID',risk_indicators:['Caller ID spoofed to match registered mobile','Voice pattern anomaly','New beneficiary'],account_age_assessment:'Established account — vishing vector'}, transaction_pattern:{pattern_type:'Vishing — phone banking impersonation',anomalies:['Spoofed caller ID matching registered mobile','Voice pattern mismatch flagged by system','First-time beneficiary for high-value NEFT'],velocity_assessment:'Single high-value transfer immediately after phone banking session'}, risk_assessment:'Caller ID spoofing combined with voice pattern anomaly and a first-time beneficiary NEFT is a high-confidence vishing attack. Recommend blocking the transfer and calling the customer back on a verified number.', processing_time_ms:1580, model_used:'claude-opus-4-6' },
  { case_id:'CASE-011', alert_type:'CARD_FRAUD', risk_level:'CRITICAL', risk_score:88, recommended_action:'BLOCK', amount:445000, currency:'INR', received_at:'2024-06-03T02:30:00Z', investigation_narrative:'Credit card account maintained consistent repayment for 14 months, then maxed all 3 linked cards (₹4,45,000 combined) in a single night across fuel stations, jewellery stores, and electronics. No repayment received. Account holder unreachable. Bust-out fraud pattern.', flags:['Bust-out pattern','Multi-card maxout','Unreachable account holder','Atypical merchant mix'], confidence:0.94, entity_profile:{summary:'Established credit customer — 14 months consistent repayment followed by sudden full card maxout',risk_indicators:['All 3 cards maxed in one night','Atypical merchant categories','Account holder unreachable'],account_age_assessment:'14-month cultivated credit profile — strategic bust-out'}, transaction_pattern:{pattern_type:'Bust-out fraud',anomalies:['3 cards maxed simultaneously — ₹4.45L','Mixed merchant types: fuel, jewellery, electronics','02:30 AM transaction cluster','14-month impersonation of legitimate customer'],velocity_assessment:'Full exposure liquidated in single overnight session'}, risk_assessment:'14 months of consistent repayment followed by simultaneous maxout of all linked cards across high-liquidity merchant categories in a single night is a textbook bust-out fraud. Account has been strategically cultivated for credit limit buildup prior to fraud execution.', processing_time_ms:2210, model_used:'claude-opus-4-6' },
  { case_id:'CASE-012', alert_type:'AML', risk_level:'MEDIUM', risk_score:61, recommended_action:'REVIEW', amount:125000, currency:'INR', received_at:'2024-06-03T10:15:00Z', investigation_narrative:'Customer transferred ₹1,25,000 to an account that has received identical ₹1-2L transfers from 47 different accounts in the past 30 days. Destination account entity registered as a "wealth management firm" but not SEBI-registered. Pattern consistent with Ponzi collection account.', flags:['Ponzi collection pattern','Unregistered investment firm','Mass inflow destination','Investor victim indicator'], confidence:0.68, entity_profile:{summary:'Customer likely a victim — transferring to a suspected Ponzi collection account',risk_indicators:['Destination received 47 similar transfers','Recipient not SEBI-registered','Investment scheme language in purpose field'],account_age_assessment:'Legitimate customer — possible fraud victim'}, transaction_pattern:{pattern_type:'Ponzi scheme — victim inflow',anomalies:['Destination account received 47 similar transfers in 30 days','Recipient claims to be wealth manager — unregistered','Purpose field: "investment returns plan"'],velocity_assessment:'Steady victim inflow pattern to aggregation account'}, risk_assessment:'Customer appears to be a victim of an unregistered investment scheme. Destination account shows classic Ponzi collection characteristics. Recommend flagging both the destination account for investigation and notifying the originating customer.', processing_time_ms:1740, model_used:'claude-opus-4-6' },
  { case_id:'CASE-013', alert_type:'AML', risk_level:'HIGH', risk_score:74, recommended_action:'ESCALATE', amount:890000, currency:'INR', received_at:'2024-06-03T14:00:00Z', investigation_narrative:'Import payment of ₹8,90,000 to a UAE supplier for "electronic components." Same supplier has received ₹2.3Cr from 8 different Indian entities this quarter. Invoice value exceeds market price by ~40% per commodity intelligence. Trade-based money laundering suspected.', flags:['TBML indicator','Over-invoicing','Multiple payers to single foreign entity','High-risk jurisdiction'], confidence:0.77, entity_profile:{summary:'Import business — payment pattern and invoice pricing inconsistent with legitimate trade',risk_indicators:['Invoice 40% above market price','Same UAE supplier received ₹2.3Cr from 8 entities','High-risk jurisdiction (UAE FATF grey list history)'],account_age_assessment:'Established import business — anomalous pricing pattern'}, transaction_pattern:{pattern_type:'Trade-based money laundering — over-invoicing',anomalies:['Invoice value ~40% above commodity market rate','Single foreign entity receiving from 8 Indian companies','₹2.3Cr aggregate Q3 inflow to UAE supplier'],velocity_assessment:'Systematic over-invoicing across multiple unrelated entities'}, risk_assessment:'Invoice pricing 40% above market rate combined with the same UAE supplier receiving payments from 8 unrelated Indian entities is a high-confidence trade-based money laundering indicator. Recommend requesting underlying trade documents and filing STR.', processing_time_ms:1990, model_used:'claude-opus-4-6' },
  { case_id:'CASE-014', alert_type:'ACCOUNT_TAKEOVER', risk_level:'CRITICAL', risk_score:97, recommended_action:'BLOCK', amount:680000, currency:'INR', received_at:'2024-06-03T21:45:00Z', investigation_narrative:'SIM for registered mobile reissued at a retail outlet 3 hours before ₹6,80,000 in NEFT transfers. OTPs for all 4 transactions delivered to new SIM. Account holder\'s registered mobile went inactive at 18:32. 4 transfers to 4 different first-time beneficiaries. Classic SIM swap attack.', flags:['SIM swap confirmed','OTP delivered to new SIM','Multiple first-time beneficiaries','Mobile deactivation pre-fraud'], confidence:0.99, entity_profile:{summary:'Account compromised via SIM swap — attacker controls OTP channel',risk_indicators:['SIM reissued 3hr before transfers','Original mobile deactivated at 18:32','All 4 OTPs to new SIM'],account_age_assessment:'Established account — OTP channel fully compromised'}, transaction_pattern:{pattern_type:'SIM swap — OTP channel compromise',anomalies:['SIM reissued at retail outlet 3hr before attack','Registered mobile deactivated 18:32','4 transfers × 4 new beneficiaries within 22 minutes','₹6.8L total exposure'],velocity_assessment:'4 authenticated transfers in 22 minutes — maximum velocity attack'}, risk_assessment:'SIM reissuance at a retail outlet followed immediately by OTP-authenticated transfers to multiple new beneficiaries is a confirmed SIM swap fraud. The account holder has been locked out of their OTP channel. Immediate block and customer notification required.', processing_time_ms:1530, model_used:'claude-opus-4-6' },
];
